export const CannonsConfig = {
  dumb: {
    cost: 2,
    range: 0,
    damage: 0,
    fireRate: Infinity,
    upgradeCost: 0,
    projectileSpeed: 0,
    name: 'Wall',
    explosionRadius: 0,
  },
  basic: {
    cost: 5,
    range: 60,
    damage: 10,
    fireRate: 1500,
    upgradeCost: 5,
    projectileSpeed: 4,
    name: 'Basic',
    explosionRadius: 0,
  },
  rocket: {
    cost: 15,
    range: 70,
    damage: 5,
    fireRate: 800,
    upgradeCost: 20,
    projectileSpeed: 5,
    name: 'Rocket Launcher',
    explosionRadius: 50,
  },
  sniper: {
    cost: 50,
    range: 100,
    damage: 50,
    fireRate: 4000,
    upgradeCost: 50,
    projectileSpeed: 40,
    name: 'Sniper',
    explosionRadius: 0,
  },
  freeze: {
    cost: 50,
    range: 80,
    damage: 10,
    fireRate: 1500,
    upgradeCost: 75,
    projectileSpeed: 1,
    name: 'Freezer',
    explosionRadius: 0,
  },
} as const;

export type CannonType = keyof typeof CannonsConfig;
