name: Push to GitHub Container Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'
      - name: Set production URLs
        run: |
          echo "PROD_PUBLIC_URL=${{ vars.PROD_PUBLIC_URL || 'https://towerdefense-56.ya-praktikum.tech' }}" >>${GITHUB_ENV}
          echo "PROD_INTERNAL_URL=${{ vars.PROD_INTERNAL_URL || 'http://server:3001' }}" >>${GITHUB_ENV}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push client image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.client
          push: true
          build-args: |
            EXTERNAL_SERVER_URL=${{ env.PROD_PUBLIC_URL }}
            INTERNAL_SERVER_URL=${{ env.PROD_INTERNAL_URL }}
          tags: ghcr.io/${{ env.OWNER_LC }}/${{ github.event.repository.name }}/client:${{ github.sha }}

      - name: Build and push server image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.server
          push: true
          build-args: |
            PROD_CLIENT_ORIGIN=${{ env.PROD_PUBLIC_URL }}
          tags: ghcr.io/${{ env.OWNER_LC }}/${{ github.event.repository.name }}/server:${{ github.sha }}
